version: "3.3"
services:
  user_api:
    build: .
    ports:
      - "5050:5050"
    command: python user.py
    volumes:
      - ./:/app

  file_api:
    build: .
    ports:
      - "5051:5051"
    command: python file.py
    volumes:
      - ./:/app