# Lo mismo que en el Dockerfile de usuario. Empezamos con Python puro.
FROM python:3.11-slim

# Nos metemos en la carpeta /app del contenedor
WORKDIR /app

# Instalamos Quart y otras librerías
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el archivo de código específico para este microservicio (file.py)
COPY file.py .

# Le avisamos a Docker que este se comunica por el puerto 5051
EXPOSE 5051

# Comando final para ejecutar la aplicación de ficheros
CMD ["python", "file.py"]
