# El archivo docker-compose.yml nos permite levantar múltiples contenedores de Docker a la vez con un solo comando.
version: '3.8' # Versión del formato del archivo (la 3.8 es estándar)

services:
  # ==========================================================
  # 1. SERVICIO DE USUARIOS (microservicio 1)
  # ==========================================================
  servicio-usuario:
    build:
      context: . # Busca los ficheros para construir la imagen en la carpeta actual (el punto)
      dockerfile: Dockerfile.usuario # Le decimos explícitamente qué fichero leer para este servicio
    ports:
      # Conecta el puerto 5050 de mi ordenador con el puerto 5050 del contenedor
      - "5050:5050"
    volumes:
      # Montamos la carpeta './almacenamiento' de nuestro ordenador dentro de '/app/almacenamiento' del contenedor.
      # Así, cuando se apague el contenedor, los JSON de usuarios no se perderán.
      - ./almacenamiento:/app/almacenamiento
    environment:
      # Le pasamos la clave secreta al contenedor a través de una variable de entorno.
      - SECRET_UUID=${SECRET_UUID}

  # ==========================================================
  # 2. SERVICIO DE FICHEROS (microservicio 2)
  # ==========================================================
  servicio-fichero:
    build:
      context: .
      dockerfile: Dockerfile.fichero # Usa su propio Dockerfile para aislar dependencias si hiciera falta
    ports:
      # Conecta el puerto 5051 de mi ordenador con el puerto 5051 del contenedor (tienen que ser distintos)
      - "5051:5051"
    volumes:
      # Compartimos EXACTAMENTE la misma carpeta de almacenamiento con el otro microservicio.
      - ./almacenamiento:/app/almacenamiento
    environment:
      # Le pasamos EXACTAMENTE la misma clave maestra, para que cuando 'user.py' calcule el token,
      # 'file.py' calcule matemáticamente el mismo resultado y lo dé por válido.
      - SECRET_UUID=${SECRET_UUID}
