# Un Dockerfile es como una receta de cocina para crear una máquina virtual (contenedor).
# En este caso le decimos a Docker que queremos que instale Linux con Python 3.11 preinstalado.
# (Usamos la versión 'slim' que ocupa menos megas en disco duro).
FROM python:3.11-slim

# Creamos una carpeta llamada /app dentro del contenedor y nos metemos en ella.
# A partir de ahora todo se ejecuta aquí dentro.
WORKDIR /app

# Copiamos el archivo de las dependencias desde nuestro ordenador al contenedor.
COPY requirements.txt .

# Le decimos a Python (pip) que instale las librerías que necesitamos (ej: Quart).
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos nuestro archivo de código (user.py) al contenedor.
COPY user.py .

# Le avisamos a Docker que nuestro programa se va a comunicar por el puerto 5050.
EXPOSE 5050

# Por último, ¿qué tiene que ejecutar la terminal del contenedor cuando arranque? 
# Esta instrucción arranca nuestro código.
CMD ["python", "user.py"]
